### ISSUE TITLE
Broken compat with REI

### ISSUE THREAD

**Issue by shBLOCK** [CyclopsMC/IntegratedTerminals#103]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crash when checking recipe (pressing r) via REI in the terminal.
(Not sure if this should instead be an REI issue)

#### Steps to reproduce the problem:

1. Install REI
2. Setup a basic item network with a terminal
3. Try pressing r while hovering an item in the terminal

#### Versions:

- This mod: 1.4.7
- Minecraft: 1.19.2
- REI: 9.1.619

#### Log file:
https://pastebin.com/q3M16Pa0

**Comment by rubensworks** [comment]
Thanks for reporting!
