### ISSUE TITLE
Crashes with EMI

### ISSUE THREAD

**Issue by brisingraerowing** [CyclopsMC/IntegratedTerminals#104]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Game crashes when opening a terminal with EMI installed

#### Steps to reproduce the problem:

1. Install Integrated Dynamics / Terminals / Tunnels, JEI, and EMI
2. Set up a basic storage network
3. Open the terminal

#### Expected behaviour:

Terminal opens and is useable.

____

#### Versions:

- This mod: 1.4.7
- Minecraft: 1.19.2
- Forge: 43.2.14

#### Log file:

[Crash Log](https://gist.github.com/brisingraerowing/f6d08979d7a1f35ecac2aed8023c0a1e)

**Comment by rubensworks** [comment]
Thanks for reporting!
