### ISSUE TITLE
Interface GUI shifts

### ISSUE THREAD

**Issue by Guslloween** [CyclopsMC/IntegratedTerminals#105]
#### Issue type:

- :bug: Interface = problem
____

#### Short description:

The terminal hud gets messed up when energy is added and the filter is set to show both items in stock and craftable items, this started when add the crafting (crafting works, terminal bugs).

#### Steps to reproduce the problem:

1. Create a system
2. Put a terminal to identify the storage
3. Create a crafting station e connect it to a system
4. Open the terminal
5. Change the config to show both items (Craftable and Storage)
6. Enjoy the grid.

#### Expected behaviour:

The terminal grid doesn't bug.

____

#### Versions:

- This mod: IntegratedTerminals-1.20.1-1.4.8     IntegratedCrafting-1.20.1-1.1.3
- Minecraft: 1.20.1
- Forge: 47.1.0

#### Log file:

https://imagebin.ca/v/7TLVY3241mML
[https://imagebin.ca/v/7TLVY3241mML]

**Comment by rubensworks** [comment]
Thanks for reporting!
