### ISSUE TITLE
[1.20.1] Modloading error when starting server. Not every boot, but sometimes.

### ISSUE THREAD

**Issue by Gbergz** [CyclopsMC/IntegratedTerminals#107]
#### Issue type:

- :bug: Bug 

____

#### Short description:
When starting server, sometimes it results in a modloading error.
Happens frequently enough to be annoying and me wanting to report it.

#### Steps to reproduce the problem:
1. Install mod.
2. Start server
3. Modloading error.
4. Profit.

#### Expected behaviour:
No modloading errors when starting servers.

____

#### Versions:

- This mod: 1.4.9
- Minecraft: 1.20.1
- Forge: 47.1.3

#### Log file:
Crash-report: https://gist.githubusercontent.com/Gbergz/ece2f10d1e27139596766fc90a600c6c/raw/7021fbbeb19d366680c78d63b99fff987d87e4b9/gistfile1.txt

**Comment by rubensworks** [comment]
Thanks for reporting!
