### ISSUE TITLE
Crush with REI 

### ISSUE THREAD

**Issue by belovres** [CyclopsMC/IntegratedTerminals#108]
#### Issue type:

- :bug: Bug 

____

#### Short description:
The game crashes when you click on an item in the network (or craft).
Modpack: Valhelsia 6 beta 12

#### Steps to reproduce the problem:

1. Create a logical network
2. Connecting the storage terminal
3. Click on any item
4. Crush

#### Expected behaviour:
Taking an item, or starting crafting it.

____

#### Versions:

- This mod: 1.4.10
- Minecraft: 1.20.1
- Forge: 47.1.3
- REI plugin: 12.0.55

#### Log file:
Pastebin log [https://pastebin.com/RaL1xfa8](url)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This seems to be an issue with REI, as this mod does not explicitly support REI. Best to report it to them. Happy to make changes here if that would be necessary.
