### ISSUE TITLE
Ghost items keep stacking indefinitely

### ISSUE THREAD

**Issue by WayDougwas** [CyclopsMC/IntegratedTerminals#109]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I tried to make a subnet with item interface to filter different stores by channel, so I see the number of items in the terminal keep increasing and when it picks up an item I get the original number of items.
#### Steps to reproduce the problem:

1.Connect item interface in some storage.
2.Place one cable in the interface just for place another interface
3.Place a cable in front of the interface
4.Connect another interface aiming in the cable in front of the second interface
5.Place some cable just for place a terminal
something like this:
![image](https://github.com/CyclopsMC/IntegratedTerminals/assets/89326159/5217019d-80c9-40cf-b831-e378500726a7)

#### Expected behaviour:
See exactly number of items from main storage

____

#### Versions:

- This mod: 1.4.9
- Minecraft: 1.19.2
- Forge: forge-43.2.0

#### Log file:
n/a

**Comment by rubensworks** [comment]
Thanks for reporting!
