### ISSUE TITLE
recipe sticks from crafting interface to player crafting

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedTerminals#11]
#### Issue type:

- :bug: Bug

____

#### Short description:

whenever a valid recipe is made in the crafting tab of a terminal and viewed, the same item will appear in the player's 2x2 inventor recipe grid
#### Steps to reproduce the problem:

1. create a network with a storage interface and terminal
2. put in a recipe in the crafting tab [e.g. pickaxe]
3. close the terminal gui with the valid recipe awaiting completion in the 3x3
4. open the inventory, and the player's 2x2 output will show the output of the terminal [e.g. pickaxe]

attempting to take the item will cause it to dissapear
#### Expected behavior:

i expected that it wouldn't do that
____

#### Versions:

- This mod: 1.0.1
- Minecraft: 1.12
- Forge: 14.23.5.2781

**Comment by rubensworks** [comment]
Huh, nice find!
