### ISSUE TITLE
1.20.1 When Crafting It Affects the Entire Server 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [CyclopsMC/IntegratedTerminals#110]
#### Issue type:

[09.11 04:56:36] [Server] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 7344ms or 146 ticks behind
[09.11 04:57:49] [Server] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 3257ms or 65 ticks behind
[09.11 04:58:57] [Server] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 53017ms or 1060 ticks behind

This lag is directly linked to manual crafting jobs.

____

#### Short description:

I have been running test with my wife and it seems like crafting is done serverside which absolutely tanks performance serverside.

#### Steps to reproduce the problem:

Ugh I think the simplest way is join my world and I can op you or ... not sure. https://legacy.curseforge.com/minecraft/modpacks/fiction-friction-pixelmon Use pack 26.0.0 (Unless server browser says otherwise.

____

#### Versions:

- This mod: IntegratedCrafting-1.20.1-1.1.6.jar
- Minecraft: 1.20.1
- Forge: 47.2.4

#### Profiler output:

https://spark.lucko.me/tHGb2t0TML

#### Notes:
Of course during testing I couldn't produce it 100% of the time >_> At any rate ... Let me know if you want me to pressure things in a specific way ...

**Comment by rubensworks** [comment]
Are you sure you provided the right spark log? Because I only see ticking entities in your log....
<img width="1172" alt="Screenshot 2023-11-09 at 08 24 12" src="https://github.com/CyclopsMC/IntegratedTerminals/assets/440384/b1eebae0-0ca4-4583-b8bf-36ea74cb089e">

**Comment by P3rf3ctXZer0** [comment]
Yeah ... at any rate I am trying to curb Cobblemon ... its strange because in the first 30 mins on server when large crafting jobs take place it caused complete server wide lag. I promise this is not a false lag report ... Its just seems like after I modded configs the lag is significantly less.

This is what I set.

``Integrated Dynamics (Fixes Server Wide Lag)
	terminalStoragePacketMaxRecipes = 20 
	craftingPlannerThreads = 3
	terminalStoragePacketMaxInstances = 50``
	
ON the other hand these settings created an issue ... when browsing large network cursor is stuttering and hiccuping.

**Comment by P3rf3ctXZer0** [comment]
If it is more effective I can reset configs and do some video recording of both the server logger and the game at same time. ...

**Comment by rubensworks** [comment]
@P3rf3ctXZer0 At first glance, I don't think those config options you changes should have any influence on server lag when crafting jobs are being executed.
Perhaps there was some other issue that arose by chance around the same time as your crafting jobs?
That would explain the lack of mentions of ITerms in your spark log.

But if I understand correctly, the lag does not occur anymore on your end. I guess we can close this issue then?

**Comment by P3rf3ctXZer0** [comment]
Thanks for the fix it works great!
