### ISSUE TITLE
Shift-clicking energy into your inventory does not update count of energy in network unless it is drained completely

### ISSUE THREAD

**Issue by Ulysses2** [CyclopsMC/IntegratedTerminals#111]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Storage terminals allow you to shift-click energy out of them to charge batteries in your inventory.
However, if there is more energy in your network than can fit in the battery, the network does not realize it has lost any energy and will say it has more than it actually does.

#### Steps to reproduce the problem:

1. Install Integrated Terminals and its dependencies. Make a creative superflat world.
2. Grab an empty 1M battery, a full 4M battery, a logic cable, and a storage terminal from the creative inventory
3. Put down the logic cable, 4M battery, and storage terminal to make a network.
4. Open the storage terminal, go to energy tab, and shift-click on the 4,000,000 FE present.
5. The network will say it has 4M FE still in it, despite the battery connected to the network clearly containing 3M.

If you now shift-click the battery in your inventory, your terminal will now say it has 5,000,000 / 4,000,000 energy in it.
Strangely, at this point, the display will now update properly - shift-clicking the energy back into your inventory will properly reduce the displayed count, although it'll always think it has 1M more energy than it actually does.

#### Expected behaviour:

Energy count decreases when using the shift-clicking feature and thus accurately shows how much energy the network has.

____

#### Versions:

- This mod: 1.4.11
- Minecraft: 1.20.1
- Forge: 47.2.0

**Comment by rubensworks** [comment]
Thanks for reporting!
