### ISSUE TITLE
When installing with Rei, opening the Storage Terminal causes a crash.

### ISSUE THREAD

**Issue by Tki-sor** [CyclopsMC/IntegratedTerminals#117]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When installing REI and opening the game for the first time, upon entering the map, using the Storage Terminal causes a crash while REI is in the loading phase.

#### Steps to reproduce the problem:

1. Open the game, enter the map, and use the Storage Terminal.

#### Expected behaviour:

It shouldn't cause a crash.
____

#### Versions:

- This mod: IntegratedTerminals-1.20.1-1.4.12   （RoughlyEnoughItems-12.0.684-forge）
- Minecraft: 1.20.1
- Forge: 47.2.18

#### Log file:
https://pastebin.com/8ZHUamQS

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Seems to be related to #108. 

This seems to be an issue with REI, as this mod does not explicitly support REI. Best to report it to them and link back here. Happy to make changes here if that would be necessary.
