### ISSUE TITLE
[Bug] Game crashes when doing something in terminal

### ISSUE THREAD

**Issue by ramazansancar** [CyclopsMC/IntegratedTerminals#119]
#### Issue type:

- :bug: Bug 

____

#### Short description:

While crafting, I have a crash problem when I connect via wireless terminal and jei is activated/deactivated.

#### Steps to reproduce the problem:

1. Open terminal.
2. Craft something.
3. See it collapse.

#### Expected behaviour:

Crashes started to increase after there were approximately 700k items in the terminal. The mining system I have set up produces hundreds of blocks and items every second.

____

#### Versions:

- Modpack: All the Mods 9 - To the Sky - atm9sky [Source](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9-to-the-sky)
- This mod: 1.20.1-1.4.14
- Minecraft: 1.20.1
- Forge: 47.2.20

#### Log file:

[https://pastebin.com/vkA9LAgf](https://pastebin.com/vkA9LAgf)

![image](https://github.com/CyclopsMC/IntegratedTerminals/assets/8878055/4c722eda-5c98-4507-a895-38d38d89c3a0)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Note to self: double-check the sorter, or check if concurrency might be an issue.

**Comment by ramazansancar** [comment]
I will continue with "Refined Storage" mode until the problem is fixed. I am waiting for your return. Thanks.

In the meantime, I can share the world saves files if it helps catch the problem. The required products will be in the chest :D
