### ISSUE TITLE
crafting recipes don't respect predicates

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedTerminals#12]
#### Issue type:

- :bug: Bug
(interaction with integrated crafting)
____

#### Short description:

when you put a predicate filter in the slot, all crafting recipes will be shown, regardless of if they are valid via the predicate

#### Steps to reproduce the problem:

1. make a system of a storage interface, terminal, and valid machine with crafting recipes [e.g. crafting table]
2. make a predicate [e.g. is damageable]
3. when the predicate is inserted into terminal, all recipes will show.

#### Expected behaviour:

recipes should respect the predicate inserted
____

#### Versions:

- This mod: 1.0.1
- Minecraft: 1.12
- Forge: 14.23.5.2781

**Comment by rubensworks** [comment]
Right, those systems were implemented independently, but never tested together.
