### ISSUE TITLE
Added support for highlighting missing items for EMI

### ISSUE THREAD

**Issue by PTALTS-LK** [CyclopsMC/IntegratedTerminals#120]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Seems to need to add missing item highlighting support for EMI here for Integrated Terminals?
https://github.com/emilyploszaj/emi/issues/570

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
This will be fixed in the next update.
