### ISSUE TITLE
Item channels keep merging, items bleed into other channels

### ISSUE THREAD

**Issue by markuskoeppen** [CyclopsMC/IntegratedTerminals#124]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Item interfaces seem to register for all channels instead of the one they are assigned to. This is inconsistent, though.

Since the minimal way to reproduce the bug is to use a terminal, I report it here.

When it discovered it in atm9sky after updating to 0.1.0, it also affected previously set-up automation using tunnels and storage access using an item interface as an access port for Refined Storage's external storage. E.g. inconsistently showing all channel contents or inserting items into wrong channel storage.
I didn't spent enough time to reliably reproduce those in a minimal setting, though.

#### Steps to reproduce the problem:

1. Place two _separate_ chests.
3. Add item interface and logic cable to each.
4. Switch the channel of one of them from 0 to 1.
5. Connect them. Add a storage terminal.

--

6. Add a dirt block to the channel 0 chest.
7. Immediately open the storage terminal.
8. The storage terminal will appear empty, then update and show 2 dirt in the "All" channel, and one in both channel 0 and 1.
9. Exit the storage terminal and open it again.
10. The storage terminal wil now correctly show the content.

--

11. Use the storage terminal to add a cobblestone block to channel 1.
12. It will also show up in channel 0 and twice in "All".
13. Exit the storage terminal and open it again.
14. The storage terminal will now correctly show the content.

#### Expected behaviour:

The storage terminal correctly shows the content of each channel, with no items bleeding in from other channels.

____

#### Versions:

Discovered in atm9sky, reproduced separately using these versions:

- This mod: 1.5.0
- Integrated Dynamics: 1.23.1
- Integrated Tunnels: 1.8.29
- Minecraft: 1.20.1
- Forge: 47.2.20

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by markuskoeppen** [comment]
I just want to note while this is a bug that exists in the current version of Integrated Dynamics that apparently is new, it might not be as gamebreaking as assumed, as I noticed the user error leading to the other bugs.

**Comment by rubensworks** [comment]
> it might not be as gamebreaking as assumed, as I noticed the user error leading to the other bugs.

What do you mean exactly? Does it lead to other bugs in this mod or in other mods?

**Comment by markuskoeppen** [comment]
> What do you mean exactly? Does it lead to other bugs in this mod or in other mods?

Not that I'm aware. I _thought_ that my automation was breaking with the update but that came from me not noticing I connected two networks. Separated them again and now the other bugs are no more.

From what I can tell, the "terminal shows items on multiple channels" bug is all I can report.
