### ISSUE TITLE
Shift-Click Out of Storage Terminal Causes Incorrect Inventory Reporting

### ISSUE THREAD

**Issue by Chris3606** [CyclopsMC/IntegratedTerminals#126]
#### Issue type:

- :bug: Bug 

____

#### Short description:

If you use shift + click to get a stack of items out of a storage terminal, the integrated dynamics storage system starts incorrectly reporting the number of items in the system.

I'm not sure if this belongs in tunnels or terminals; I can create another report if needed.

#### Steps to reproduce the problem:

1. Create a modpack with _just_ integrated terminals, integrated tunnels, integrated dynamics, and their dependencies.
2. Create a vanilla chest and place it.
3. Connect an item interface from integrated tunnels to the chest, and connect a logic cable to the item interface
4. Connect a storage terminal from integrated terminals to the same network.
5. Place 4 stacks of cobblestone into the chest
6. Open the storage terminal UI, and shift-click on the cobblestone to extract one stack.
7. One stack is withdrawn, and the chest contains 192 items; but the UI reports 35 items remaining instead of 192.

Withdrawing or adding future items of this type causes further desyncs; for example, adding items back after this often causes the storage terminal to report almost double the correct number of items.

Breaking the logic cable connected to the interface and re-placing it resolves the issue, until you shift-click again.

#### Expected behaviour:

When withdrawing items using shift-click, I would expect the system to report the actual number of items remaining.

____

#### Versions:

- This mod:
    - Integrated Terminals 1.5.2
- Dependencies
    - Integrated Dynamics 1.23.8
    - Integrated Tunnels 1.8.28
    - IntegratedTerminalsCompat v1.5.2
    - IntegratedTunnels-Compat v1.8.28
    - Cyclops Core v1.25.1
    - CommonCapabilities 2.9.4
    
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.68

#### Log file:

Not sure what log file would be valuable here since there is no crash; happy to post whatever you need though.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Possible related to #124

**Comment by rubensworks** [comment]
This was a bug in Common Capabilities.
A new release is being published now (2.9.5).
Updating to that one will fix this problem.

**Comment by Chris3606** [comment]
Awesome!  I'll give it a shot.

**Comment by Chris3606** [comment]
Checked this, works great!

**Comment by mswmaurer** [comment]
Is it possible to get this fix on NeoForge for 1.21?  Common Capabilities stops at 2.9.2 on that version. Thanks!

**Comment by rubensworks** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/common-capabilities/files/5809047

<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/44/386/120/120/636031220874205150.png" width="48" align="right"><div>CurseForge</div><div><strong><a href="https://legacy.curseforge.com/minecraft/mc-mods/common-capabilities">Common Capabilities</a></strong></div><div>Forge Capabilities that can be shared by multiple mods</div></blockquote>
