### ISSUE TITLE
Start a craft from JEI

### ISSUE THREAD

**Issue by rhullah** [CyclopsMC/IntegratedTerminals#127]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

When searching for an item I want crafted I'd like to press the `+` button in JEI to move the ingredients I do have to the crafting grid and then start auto-crafting any ingredients I don't have but have recipes for.  AE2 does this by allowing you to ctrl/cmd-click the `+` button.  Additionally, any items that need to be crafted are highlighted a different color (blue) to denote that item needs to be crafted rather than red which typically means it's not available.

#### Example

**The Setup**
1. Have recipes for: Logs -> Planks and Planks -> Chest.
2. Make sure your storage inventory has logs and iron ingots in stock (no chests).
3. Search JEI for hopper

**Expected Behavior**
1. Hovering over the `+` button would show the iron was in stock (no background color), and the planks and chest in a non-red (likely blue) color to signify those items could be auto-crafted.
2. Press ctrl/cmd while clicking the `+` button would:
  a. Move any existing in stock items to the crafting grid
  b. Prompt to auto-craft the planks
  c. Once accepting the planks auto-craft, then prompt to auto-craft the chest
3. Once the crafting was done it would be nice if the items would auto fill into the crafting grid, but AE2's behavior is to place them in storage and then the user either fills in the crafting grid or the user re-searches for the recipe and presses the `+` button again to fill the crafting grid.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Implemented; will be included in the next release.

**Comment by rhullah** [comment]
This is awesome! Thank you for your speedy and great work!
