### ISSUE TITLE
Receipt random rotation in MC 1.21.1

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedTerminals#129]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Cannot create spruce door and spruce trapdoor (bug is random)

#### Steps to reproduce the problem:

1. Create a chest, attach item interface above, attach cable above, add storage terminal with cable behind
2. Put stack of Spruce Planks inside the chest
3. Try put planks in the grid (of the Storage Terminal):
XX
XX
XX
4. Result is a trapdoor (instead the regular door)
5. Try put planks in the grid:
XXX
XXX
4. Result is a trapdoor again

Sometimes (after creation of a new world?) result in both cases is a door, and sometimes result is a trapdoor. Vanilla crafting table works fine.

___

#### Versions:

Min list of mods to reproduce:
CommonCapabilities-1.21.1-neoforge-2.9.5.jar
cyclopscore-1.21.1-neoforge-1.25.1-630.jar
IntegratedCrafting-1.21.1-neoforge-1.1.10.jar
IntegratedDynamics-1.21.1-neoforge-1.23.9.jar
IntegratedTerminals-1.21.1-neoforge-1.5.2.jar
IntegratedTunnels-1.21.1-neoforge-1.8.28.jar

- This mod: 1.1.10
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.68

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rikzun** [comment]
still sometimes get this bug, also sometimes when crafting from JEI I can sometimes completely lose some items used in crafting

https://github.com/user-attachments/assets/30fb6b96-0e78-427f-b9da-c8929fb745ff

**Comment by Jack-McKalling** [comment]
> still sometimes get this bug, also sometimes when crafting from JEI I can sometimes completely lose some items used in crafting

Could you create a new bug report for that? Considering the mod has changed in the mean time and that you're mentioning items getting voided, this is a different (or at least altered) issue. In a new report you can mention all of the needed version info and repro steps etc. Thanks.
