### ISSUE TITLE
IntegratedCrafting Requests from Storage Terminal with Nested Recipes Producing Multiple Items Resolve Incorrectly 

### ISSUE THREAD

**Issue by Chris3606** [CyclopsMC/IntegratedTerminals#131]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Not sure if this is an integrated crafting bug or storage bug; I've only been able to replicate it with the storage terminal.  It appears that if you have a recipe that uses multiple of an item, where that item uses an item whose recipe produces more than 1 of its type, the storage terminal over-estimates resource cost when you attempt to craft.

#### Steps to reproduce the problem:

1. Create a chest, and attach a item interface to it.
2. Connect a storage terminal to the same network.
3. Create a crafting table, attach a crafting interface to it, and attach it to the network.
4. Teach the crafting interface the following (valid) recipes:
    - 1 redstone block -> 9 redstone
    - 1 redstone + 1 stick -> redstone torch
    - 3 redstone torches, 3 stone, 1 nether quartz -> 1 redstone comparator
5. Place the following items in the chest:
    - 1 nether quartz
    - 3 stone
    - 1 redstone block
    - 3 sticks
6. Open the storage terminal, and request 1 redstone comparator.

The craft won't complete; it incorrectly reports that it doesn't have enough redstone blocks. it says it has one but needs 2 more.

In general, this appears to reproduce with any recipe where a nested leaf node produces more than 1 (aka redstone block produces 9 redstone and redstone is used in items used by the item you try to craft); I originally replicated this attempting to autocraft Powah components, but reduced it to integrated and vanilla recipes only for a bug report.

#### Expected behaviour:

The storage terminal should complete the craft by turning 1 redstone block into 9 redstone, using 3 of that redstone plus the sticks to create 3 redstone torches, then using those torches, the stone, and the nether quartz to create the comparator.

____

#### Versions:

- This mod:
    - Integrated Terminals 1.5.2
- Dependencies
    - Integrated Dynamics 1.23.9
    - Integrated Tunnels 1.8.28
    - IntegratedTerminalsCompat v1.5.2
    - IntegratedTunnels-Compat v1.8.28
    - Cyclops Core v1.25.1
    - CommonCapabilities 2.9.5
    - Integrated Crafting 1.1.10
    
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.68

#### Log file:

Not sure what log would be helpful here; if one is needed please let me know.

**Comment by rubensworks** [comment]
Thanks for reporting!
