### ISSUE TITLE
Dupe Bug on 1.21.1

### ISSUE THREAD

**Issue by mryel00** [CyclopsMC/IntegratedTerminals#132]
#### Issue type:

- :bug: Bug 

____

#### Short description:

You can easily dupe items in Minecraft version 1.21.1 with the storage terminal. I also tested this with 1.20.1, but the issue is not present in that version. This is most likely related to autofill.

#### Steps to reproduce the problem:

1. Build a storage setup with e.g. a chest, item interface, logic cable and a storage terminal
2. Open up the crafting grid of the storage terminal
3. Put at least 3 diamonds stacked onto each other into the crafting grid of the storage terminal
4. Shift click the output as often as you like
5. You now have a few million diamonds that you can e.g. drop or put into your chest or inventory

Note: If you use less than 3 items on the stack it will just delete the item even pulling them out of the inventory. This can also be done with basically every other combination of items, that don't create a recipe. I tested it with a fresh installation, only containing the mods listed in the Versions section.

#### Expected behaviour:

No duping or voiding of items. It's so simple, it will happen accidentally. The only question will be when.
____

#### Versions:

- This mod: 1.5.1
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.72 

Additional Mods installed:
- Cyclops Core: 1.25.1
- CommonCapabilities: 2.9.5
- IntegratedDynamics: 1.23.9
- IntegratedTunnels: 1.8.28

**Comment by rubensworks** [comment]
Thanks for reporting!
