### ISSUE TITLE
Game crashes when a key is pressed inside a terminal while using EMI

### ISSUE THREAD

**Issue by l-uiz** [CyclopsMC/IntegratedTerminals#133]
#### Issue type:

- :bug: Bug 

____

#### Short description:

IntegratedTerminals crashes when EMI is enabled and a key is pressed inside a terminal
I also couldn't open the terminal when EMI was disabled

#### Steps to reproduce the problem:
1. Make sure EMI is enabled (disabling EMI in the bottom left menu solves this)
2. Open your storage network's contents with a storage terminal
3. Press a key (esc, e, r, u, disabling EMI with ctrl + o inside a terminal also crashes)

#### Expected behaviour:

The game not crashing when a key is pressed inside a terminal
____

#### Versions:

- This mod: IntegratedTerminals-1.20.1-1.6.0
- Minecraft: 1.20.1
- Mod loader version: Forge 47.3.10 
- EMI: emi-1.1.16+1.20.1+forge

#### Log file:
https://mclo.gs/oWmtfT8

**Comment by rubensworks** [comment]
Thanks for reporting!
