### ISSUE TITLE
Performance is abysmal when crafting drawers

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedTerminals#134]
#### Issue type:

- :bug: Bug 

____

#### Short description:

https://streamable.com/7wra8b
Network in this video is just as you see, some drawers and a bunch of chests from Sophisticated Storage. Omni connector is just used for wireless access.
Crafting grid fills item by item, and it takes about 4 seconds to move each item.
Interestingly, crafting table recipe fills instantly,

#### Steps to reproduce the problem:

Reproducing this requires large pack - I'm playing a slightly altered ATM10.
I assume that terminal does a really bad job of figuring out which planks it should use to draft drawer from Functional Storage, however trying to craft crafting table which also should use `#minecraft:planks` fills grid instantly.
I have 9 pages like this of planks.
![image](https://github.com/user-attachments/assets/7058fcfa-3830-4783-8116-3f78914ec1a4)

#### Expected behaviour:

Crafting grid fills instantly.

____

#### Versions:

- This mod: 1.6.3
- Integrated Dynamics: 1.23.11
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.73

#### Log file:
Nothing interesting in logs.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you try downgrading to ID 1.23.10 to see if that has any impact? (I suspect it won't)

If no impact, could you share a profiling log as explain in https://github.com/CyclopsMC/CyclopsCore/blob/master-1.18/.github/CONTRIBUTING.md#performance-issues-snail ?

<blockquote><img src="https://opengraph.githubassets.com/c59a9f023515e6181f37f615f028ce0589b49fa31c31dfc334dca6f79addd960/CyclopsMC/CyclopsCore" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore/blob/master-1.18/.github/CONTRIBUTING.md">CyclopsCore/.github/CONTRIBUTING.md at master-1.18 · CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsMC/CyclopsCore</div></blockquote>

**Comment by Hiranus** [comment]
Downgrade fixed the issue, drawer recipe fills instantly.

I updated to 1.23.11 again and used spark profiler

https://spark.lucko.me/mbZr5cLbvO

<blockquote><img src="https://spark.lucko.me/thumb/mbZr5cLbvO.png" width="48" align="right"><div><strong><a href="https://spark.lucko.me/">spark</a></strong></div><div>spark is a performance profiler for Minecraft clients, servers, and proxies.</div></blockquote>

**Comment by rubensworks** [comment]
Thanks for the help @Hiranus.
I've reverted the change in a new release.

For reference, the reverted change will be further investigated in the future: #1412.
