### ISSUE TITLE
Game crashes when opening fluid tab

### ISSUE THREAD

**Issue by Hiranus** [CyclopsMC/IntegratedTerminals#136]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Game crashes when opening fluid tab with Functional Storage controller connected to the network via fluid interface.

#### Steps to reproduce the problem:

1. Connect Functional Storage controller to the network with fluid interface
2. Open terminal and switch to fluid tab

#### Expected behaviour:

Game doesn't crash
____

#### Versions:

- This mod: 1,6,3
- ID: 1,23,14
- Minecraft: 1,21,1
- Mod loader version: NeoForge 21.1.73

#### Log file:

[disconnect-2024-11-01_17.20.58-client.txt](https://github.com/user-attachments/files/17601763/disconnect-2024-11-01_17.20.58-client.txt)
[latest.log](https://github.com/user-attachments/files/17601772/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!
