### ISSUE TITLE
job terminal resource mode

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedTerminals#14]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

a mode for the crafting job terminal that can give an exact count of what's missing and what's available for an uncraftable task in a straight list instead of a tree

**Comment by rubensworks** [comment]
I actually really like the tree-based view :-) But sure, there could be an alternative view mode as well.

**Comment by antrobot1234** [comment]
at the very least, a better sense of how many of the item you need, so it can be "you need 5 of this item" instead of "you need 1 of this item 5 many times"
