### ISSUE TITLE
JEI experience fluid incompatibility

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedTerminals#140]
#### Issue type:

- :bug: Bug 

____

#### Short description:

If use filtering fluid interface with some tank (specifically with Liquid Experience from some mods) and specify filtering Card from JEI, then Storage Terminal doesn't show the fluid in fluids tab.
But if program this card with bucket of experience, then the liquid in the tank is shown normally.

____

#### Versions:

- This mod: IntegratedTerminals-1.21.1-neoforge-1.6.5.jar
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.180

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Is there some kind of NBT data attached to this fluid? (you should be able to read this with ID)
And could you tell me exactly which fluid+mod causes this issue?

Are you sure that you haven't been using fluids from different mods?

**Comment by uhloin** [comment]
Ah, sorry. There is 2 types of experience from 2 mods and I messed them. It's a false bug, sorry.

**Comment by rubensworks** [comment]
No worries, thanks for checking.
