### ISSUE TITLE
JEI Compat Error Log Causes Massive Client Lag

### ISSUE THREAD

**Issue by N1ghthauq** [CyclopsMC/IntegratedTerminals#141]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When looking at anvil recipes while in an integrated terminals terminal. The JEI spends an insane amount of tick time writing error logs.

I don't have logs for other recipes yet, but I do know that this issue impacts more than anvil recipes.

#### Steps to reproduce the problem:

1. Open a terminal. (I have a really large network that may be compounding the issues)
2. Find an anvil recipe to look at in JEI. I used a tool and looked at what enchants can be applied.
3. Observe lag. It can cause the game to freeze and become unresponsive, or soft crash.

#### Expected behaviour:

Check anvil recipes, and other recipes without the client lag.

____

#### Versions:

- This mod: 1.6.5
- Minecraft: 1.21.1
- Mod loader version: neoforge 21.1.80

I haven't tested this without the other mods, and I am using the latest ATM 10.
I am posting here first due to the logs pointing at the integrated terminals/jei compatibility errors.
This issue has been present for a long time, ~ATM 8 is when I first noticed this.

#### Log file:

Spark Profiler Client Side
https://imgur.com/a/RjlEUnf
[Integrated Lag.zip](https://github.com/user-attachments/files/17928124/Integrated.Lag.zip)

Error Log:
https://pastebin.com/tDxQ2SBX

If you want the full log, I will have to upload another zip file. It is too large to put in pastebin.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
This issue may already be on the radar, as mentioned here: https://github.com/CyclopsMC/IntegratedTerminals/issues/139#issuecomment-2500075141

But I'm not exactly sure, so until that issue's fix has been finalized, I'll leave this open just in case it turns out to be a separate bug.
