### ISSUE TITLE
1.20.1 - Portable Storage Terminal Network Connection Dropping while in Curios slot

### ISSUE THREAD

**Issue by ToxinZangoose** [CyclopsMC/IntegratedTerminals#143]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When equipping a Portable Storage Terminal in the curio slot (body in this case), the network disconnects the terminal.
#### Steps to reproduce the problem:

1. Open the terminal UI and connect it to a Omni Directional Connector
2. Place the network inside a compact machine for easy storage
3. Attempt to leave the compact machine and access network
4. Network is not linked or is missing when pressing the keybind

#### Expected behaviour:

I expected a remote access of my storage.
____

#### Versions:
CommonCapabilities: 2.9.4
CyclopsCore: 1.19.5
Integrated Crafting: 1.1.9
Integrated Dynamics: 1.24.0
Integrated Terminals: 1.6.3
Integrated Tunnels: 1.8.32

Forge: 47.3.12

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
I can reproduce this by setting up and connecting the network in the _nether_, going back to the overworld and then pressing the keybind.

This means the network is not in a loaded chunk, and in that situation the network will simply not work. While this is unfortunate, this is how it works and cannot be fixed. As soon as you enter the dimension of your network, the keybind instantly works again, so this is just a case of the network requiring chunk loading to work.

For now I'll close this report as "not planned", but if you have more information about your experience that is _not_ related to chunk loading, feel free to add this information and we'll look into this further.

**Comment by rubensworks** [comment]
@Jack-McKalling I'm not sure that is exactly what this issue is about.

@ToxinZangoose Does the portable terminal work if you are right next to the network?

**Comment by ToxinZangoose** [comment]
Yes, the terminal works if I am standing right next to it, but outside of the compact machine, it disconnects.
I am using FTB Chunks to load the chunk inside the compact machine.

**Comment by Jack-McKalling** [comment]
Thanks for sharing the info. It turns out if that is the case, I may have closed this too early. For further understanding what is actually the bug, please answer the following.

Does the portable terminal also still work if you use the terminal in your hotbar, while outside of the compact machine? This is to determine if it's really due to the curios slot or in fact total failure unrelated to that mod.

**Comment by ToxinZangoose** [comment]
Ok, after further testing, I can confirm the terminal works when outside of my curio slots. I also discovered that Ksyxis causes chunks to become unloaded. This may explain the loss of connection.

**Comment by Jack-McKalling** [comment]
I still cannot reproduce with the chunk forceloaded (using vanilla command), neither on hotbar nor in curios slots. Although I'm not using Ksyxis. So far it looks like it may be like you say, some other mod causing this and not necessarily the curios api, unless I'm doing something wrong.

Could you try to reproduce the problem in a clean environment, without other mods than InTe, Curios and Compact Machines installed? Going off of your original description. If you can then still reproduce it in the exact same way you are now, then I guess we need to look further into what's happening.

**Comment by ToxinZangoose** [comment]
Ok will do, I will try isolating the mods and seeing if I can find the culprit. Thank you for your time.

**Comment by ToxinZangoose** [comment]
Just tested this with the bare minimum of the mods installed and the terminals work. Looks like I will need to slowly add each mod back and see which one causes the issue.

**Comment by ToxinZangoose** [comment]
The cause was Limited Chunkloading, sorry for the inconvenience.

**Comment by rubensworks** [comment]
No problem, thanks for letting us know.
