### ISSUE TITLE
Client Crashes When Crafting a Jukebox

### ISSUE THREAD

**Issue by ToxinZangoose** [CyclopsMC/IntegratedTerminals#144]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When on a server, crafting a jukebox when there are several mods that add wood are installed, the packet size is too large and the client crashes.

#### Steps to reproduce the problem:

1. Open storage terminal
2. Highlight jukebox in JEI
3. Press left click
4. Crash to main menu

#### Expected behavior:

A friend wanted a boombox from Etched and it crashed him when he tried to make it and myself when I tried too.
____

#### Versions:

- CommonCapabilities: 2.9.4
- CyclopsCore: 1.19.5
- Integrated Crafting: 1.1.9
- Integrated Tunnels: 1.8.32
- Integrated Dynamics: 1.24.0
- Integrated Terminals: 1.6.3
- Etched: 3.0.2
- Minecraft: 1.20.1
- Mod loader version: Forge 47.2.12

#### Log file:

https://mclo.gs/FBzhVcJ

This was tested on a server and only crash myself and my friend when we both tried to craft a jukebox.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I can't see anything in the logs unfortunately. Could you share a log that contains the error message you are getting?

**Comment by ToxinZangoose** [comment]
I linked the log file in the original post, but this is the error I get when crafting a jukebox on a server with Etched installed.
![image](https://github.com/user-attachments/assets/6f068387-6c6a-4bb1-a5d8-48409638c707)

**Comment by rubensworks** [comment]
The problem is that I don't see this `DecoderException` being mentioned in your logs.
Are you sure you shared the correct one?

**Comment by ToxinZangoose** [comment]
The log file does not mention the internal DecoderException for some reason, but this was after I tried rejoining the server and attempting to craft the jukebox. In one of the other issues, Limited Chunkloading caused chunks to unload even when force loaded with FTB Chunks.

**Comment by rubensworks** [comment]
Could you try it again, until you can produce a log that contains this `DecoderException`?

**Comment by ToxinZangoose** [comment]
After testing the storage network on a singleplayer world, I am unable to reproduce the issue even when the network has different types of wood/planks and a stack of diamonds in it. 

Since I don't own the server, I don't think I can get the crash log. Sorry that this can't be resolved on my end, I think this was a server issue more than a mod issue.

**Comment by rubensworks** [comment]
Ok, no worries, thanks for checking! Should you gain any further information in the future, be sure to let us know.
