### ISSUE TITLE
➕ Clear the crafting grid reverse (config)

### ISSUE THREAD

**Issue by larskr96** [CyclopsMC/IntegratedTerminals#17]
Hey suggestion to add a config that reverse the button to clear the crafting grid. so when you normally click it goes in too storage and if you shift click it goes too the player

**Comment by GreyMario** [comment]
Would just like to say this is tripping up people (like me) who are used to AE2 and RS behavior of the grid clearing into storage, so having it reversed by default would be... preferable.

Changing the recipe via JEI also moves the items into the player's inventory, again counter to the habits of AE2/RS users.

**Comment by rubensworks** [comment]
Feel free to submit a PR for this, as I probably won't have time to implement this very soon, I have enough bugs (and other feature requests) on my hands for the near future.

**Comment by Fedwick** [comment]
that would be nice because when you auto complete a recipe and items from a previous craft are left in the crafting grid they end up in your inventory !
