### ISSUE TITLE
MouseTweaks/InvTweaks support

### ISSUE THREAD

**Issue by jinkhya** [CyclopsMC/IntegratedTerminals#18]
#### Issue type:

- :bug: Bug

____

#### Short description:

Hello, 
I found 2 issues with mousetweaks : 
1st issue :
When you input multiple items in the terminal with mouse tweaks, aka holding shift and left click and moving the mouse over all the items in your inventory you, the first item/stack on wich you started shift clicking doesn't go in (you have to go over it a second time) 

2nd issue : 
the items inserted that way don't go in the storage, they directly go in the crafting tab 

Here's a video that might help you understand what I mean by that : 
https://streamable.com/c8ztm

#### Steps to reproduce the problem:

1. Hold Shift and Left click together starting on one of the item slot to insert items in the terminal
2. move your mouse over all the items you want to insert. 
3. check the crafting tab.

#### Expected behaviour:

Items should go in the storage just like when you shift click one item slot at the time. :)
____

#### Versions:

- This mod: IntegratedTerminals-1.12.2-1.0.1.jar
- MouseTweaks-2.9-mc1.12.2.jar
- Minecraft: 1.12.2
- Forge: 2808

**Comment by rubensworks** [comment]
MouseTweaks is not supported. We/they should have to add custom support in order for this mod to work with it.

**Comment by jinkhya** [comment]
Alright no worries, thanks for the answer !

**Comment by invention64** [comment]
Would it be possible to have a warning message in chat if you load a game with both mods loaded? I've been looking for a solution for a while and it's not exactly obvious.

**Comment by theboo** [comment]
Instead of implicit support, would it be possible to just make the crafting grid tab inaccessible to inputs when you have the storage tab up? Would be a good middle ground IMO, I'm definitely not a dev so idk how simple that would be haha

**Comment by rubensworks** [comment]
That should in fact already be the case.

**Comment by theboo** [comment]
Seems to not be the case, at least with Inventory essentials shift+click swipe, ctrl+shift+click all of one item and space+click entire inventory (gif below)... Guess it could be the way they are doing it? I've tested with simple storage, Tom's storage, pretty pipes and RS mods and don't see this happen with those mods, just IT which I'm absolutely loving for a storage manager/network right now.

Totally understand if it takes awhile or never gets any sort of "fix" just trying to give a little more input. 

Thanks for everything you do!

https://gyazo.com/63b87d66786e65c4451f1fcef8c9cfc5 

<blockquote><img src="https://i.gyazo.com/thumb/1200/63b87d66786e65c4451f1fcef8c9cfc5-gif.gif" width="48" align="right"><div><img src="//assets2.gyazo.com/favicon.ico" height="14"> Gyazo</div><div><strong><a href="https://gyazo.com/63b87d66786e65c4451f1fcef8c9cfc5">Gyazo</a></strong></div><div>&nbsp;</div></blockquote>

**Comment by rubensworks** [comment]
Thanks for the input! This would probably require a dedicated implementation for compat.

**Comment by Random832** [comment]
How exactly does the shift-click feature in the terminal work? I noticed that even without MouseTweaks, it transfers the item on button release instead of on button click like other GUIs. By itself this doesn't matter much, but it might be the key to understanding what's going on.

EDIT: It looks like it's handled in the ContainerScreenTerminalStorage.mouseClicked method, rathe than in the container's quickMoveStack method as most GUIs do it. So it seems MouseTweaks is causing quickMoveStack [in ContainerExtended, if I'm following the code correctly] to be called directly which results in the behavior we see.

**Comment by rubensworks** [comment]
@Random832 Yeah, thw shift-click code could definitely be re-implemented using `quickMoveStack`. PRs are most welcome :-)
