### ISSUE TITLE
Crash on entering controls menu

### ISSUE THREAD

**Issue by pzrc** [CyclopsMC/IntegratedTerminals#2]
#### Issue type:

- :bug: Bug

____

#### Short description:

When opening the controls menu, Minecraft crashes with a NullPointerException. Removing Integrated Terminals fixes this issue.

#### Steps to reproduce the problem:

1. Start up Minecraft.
2. Options -> Controls
3. Minecraft should crash.

#### Expected behaviour:

Expected to open up the controls menu to change my auto-jump setting.

____

#### Versions:

- This mod: 1.0.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2807

#### Log file:
https://pastebin.com/reP6201Y

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
