### ISSUE TITLE
GUI height adjustment

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedTerminals#21]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

a button added to the left column that changes how many rows of inventory the GUIs can display (similar to refined storage)

**Comment by bangplaysgames** [comment]
I would also suggest perhaps a slight GUI redesign to move the crafting grid underneath the inventory, in order to allow the inventory full width.
