### ISSUE TITLE
itemized chicken problem

### ISSUE THREAD

**Issue by Yoghurt4C** [CyclopsMC/IntegratedTerminals#23]
#### Issue type:

- :bug: Bug

____

#### Short description:
![image](https://user-images.githubusercontent.com/11313954/53293360-a2350b80-37e3-11e9-976f-2a41191c26c9.png)
the terminal seems to grab the wrong textures for certain items while scrambling them in the process, resulting in mismatches and outright missing textures

#### Steps to reproduce the problem:

1. take [Chickens](https://github.com/setycz/ChickensMod), [Coop](https://minecraft.curseforge.com/projects/coop) and Integrated Terminals
2. put a chicken item from Coop into a chest and look it up via a terminal
#### Expected behaviour:
![image](https://user-images.githubusercontent.com/11313954/53293392-212a4400-37e4-11e9-9c24-b05ac0385ee2.png)

#### Versions:

IT 1.0.3
forge 2808

**Comment by rubensworks** [comment]
Heh, that's funny :-)
