### ISSUE TITLE
broken textures

### ISSUE THREAD

**Issue by rsclapper** [CyclopsMC/IntegratedTerminals#24]
#### Issue type: Broken Textures with Pam's Harvest Craft

- :bug: Bug

____

#### Short description:

Added a peanut butter sandwich as a craft recipe, looked at the storage terminal to craft said sandwhich and see a broken texture. 

![image](https://user-images.githubusercontent.com/2728560/53759253-db2d4a00-3e8d-11e9-9bf6-b402942e68bb.png)

#### Steps to reproduce the problem:

1. add pam's recipe as a crafting item
2. open storage terminal
3. view craft able items

#### Expected behaviour:

should see texture of item

____

#### Versions:

- This mod: 1.12.2-1.04
- Minecraft: 1.12.2
- Forge: 14.23.5.2810

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Probably related to #23.
