### ISSUE TITLE
Item in cursor switching by itself

### ISSUE THREAD

**Issue by Blockguy24** [CyclopsMC/IntegratedTerminals#29]
#### Issue type:

- :bug: Bug

____

#### Short description:

When taking an item stack out of the terminal while the terminal is set to sort on item amount, and dragging with the left or right mouse button, after letting go the items left in the cursor switch with another one.

#### Steps to reproduce the problem:

1. Set up as follows:
![image](https://user-images.githubusercontent.com/21016331/55871503-1d088900-5bce-11e9-81cf-b7851d1b3a31.png)
Inside chest:
![image](https://user-images.githubusercontent.com/21016331/55871551-3c9fb180-5bce-11e9-8026-7e9511086550.png)
2. Open terminal, select Item Storage tab and set Item Amount to Descending
3. Click on the Stone item stack, and click and drag it across the first two slots of your inventory
4. Item picked up should now be granite  

#### Expected behaviour:

Item picked up should stay the same item.
____

#### Versions:

- This mod: 1.12.2-1.0.6
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

#### Log file:

[Log File](https://pastebin.com/0V8xmYng)

**Comment by rubensworks** [comment]
That doesn't sound right indeed, thanks for reporting!

**Comment by Blockguy24** [comment]
Here's a video: [Link](https://drive.google.com/open?id=1-BJKQGjfEwCCDcxk43gbE9Dl2HVq4lVk)
