### ISSUE TITLE
Mysterious slot in Integrated Terminal UI

### ISSUE THREAD

**Issue by Flanks255** [CyclopsMC/IntegratedTerminals#3]
[imgur](https://imgur.com/YgvvqXp)
[imgur](https://imgur.com/ZHocyUu)

Items can(sometimes) be put in that slot, and sometimes shift clicked into it.

As seen with:
Forge: 14.23.5.2808
Terminals 1.0.1

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
Will be fixed in the next release.

Should you still encounter with this in the future, be sure to let me know here!
