### ISSUE TITLE
Storage terminal crafting tab ignores toggle button.

### ISSUE THREAD

**Issue by Flanks255** [CyclopsMC/IntegratedTerminals#30]
If you have "Auto-refill crafting grid" disabled, it still refills the grid after you craft something, even though it is set to disabled.

Integrated Terminals: 1.0.6

**Comment by rubensworks** [comment]
Is that in singleplayer or on a server?

**Comment by Flanks255** [comment]
Server, i was trying to use the option to stop my inventory from filling up while crafting things(Every time i load a recipe from JEI it dumps the remains of the previous craft into my inventory).
