### ISSUE TITLE
Removing the storage terminal with wrench causes the item in the crafting grid to drop

### ISSUE THREAD

**Issue by Loner-Knowledge** [CyclopsMC/IntegratedTerminals#35]
#### Issue type:

- :bug: Bug

____

#### Short description:

When the storage terminal is removed with wrench, the item in the crafting grid will drop.
This will copy items.

#### Steps to reproduce the problem:

1. Get a chest with an item interface and a storage terminal.
2. Place any items to the crafting grid of the storage terminal.
3. Use wrench to remove the storage terminal, then the storage terminal itself and the item in the crafting grid will drop.
4. Put the removed storage terminal back into place, you will see the item in the crafting grid still there.

#### Expected behaviour:

Items in the crafting grid should not be dropped when the storage terminal is removed with wrench, because they are already stored in the NBT of the storage terminal.

____

#### Versions:

- This mod: 1.0.6
- Minecraft: 1.12.2
- Forge: 14.23.5.2815

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
