### ISSUE TITLE
Crash when accessing Storage terminal

### ISSUE THREAD

**Issue by Shiruki** [CyclopsMC/IntegratedTerminals#36]
#### Issue type:

- :bug: Bug

____

#### Short description:

Game crashes occasionally when opening terminal

#### Steps to reproduce the problem:

1. I'm not able to recreate as it does not happen every time.  

#### Expected behaviour:

____Terminal Open

#### Versions:

- This mod: IntegratedTerminals-1.12.2-1.0.8
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

#### Log file:

https://pastebin.com/DPDDuV7x

**Comment by rubensworks** [comment]
Oh, that looks wrong indeed. I'm surprised it took this long for this issue to pop up. Thanks for reporting!
