### ISSUE TITLE
Crafting job terminal resetting scroll position

### ISSUE THREAD

**Issue by Naosyth** [CyclopsMC/IntegratedTerminals#38]
#### Issue type:

- :bug: Bug

____

#### Short description:

When scrolling through a crafting plan in a crafting job terminal, the scroll bar gets reset to the top every second. In the GIF below, I am never manually scrolling up or re-expanding the sections.

![crafting-terminal-bug](https://user-images.githubusercontent.com/1323992/59162979-10f65600-8aaf-11e9-9870-a59b005245ae.gif)

#### Steps to reproduce the problem:

1. Queue a crafting job that has enough steps to be able to scroll in the crafting terminal
2. Scroll down in crafting terminal
3. Every second you will get reset to the top of the scroll area
4. If you collapse a section, it will automatically get expanded with the next refresh.

#### Expected behaviour:

Your scroll position should remain the same when the gui updates. It should only scroll back up if the crafting plan becomes shorter such that your current scroll height would be out of the new scroll area. Collapsed sections should also remain collapsed.
____

#### Versions:

- Integrated Dynamics: 1.12.2-1.0.14
- Integrated Crafting: 1.12.2-1.0.7
- Integrated Terminals: 1.12.2-1.0.8
- Integrated Tunnels: 1.12.2-1.6.9
- Minecraft: 1.12.2
- Forge: 14.23.5.2837

**Comment by rubensworks** [comment]
Oh, I think I completely forgot to implement this, thanks for letting me know!

**Comment by 7eggert** [comment]
Still buggy 2021-05-22 MC 1.16.5

https://youtu.be/sExNw-g9TX4

IntegratedCrafting-1.16.5-1.0.15.jar
IntegratedDynamics-1.16.5-1.8.1.jar
IntegratedREST-1.16.5-1.1.3.jar
IntegratedTerminals-1.16.5-1.2.3.jar
IntegratedTunnels-1.16.5-1.8.1.jar


<blockquote><img src="https://i.ytimg.com/vi/sExNw-g9TX4/hqdefault.jpg" width="48" align="right"><div><img src="https://www.youtube.com/s/desktop/df22805b/img/favicon_144.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=sExNw-g9TX4">Integrated Crafting Terminal misfunction</a></strong></div></blockquote>

Edit: Scrolling does not work at all.

**Comment by rubensworks** [comment]
@7eggert I see some clicking on the video, but no scrolling using the scrollbar. Are you sure you sent the correct video?

**Comment by 7eggert** [comment]
I remembered that I didn't scroll in the video after I sent it but made no new one. The scrollbar has no effect at all but rather went to bed.

**Comment by rubensworks** [comment]
@7eggert I looked at the video again, and there doesn't seem to be a problem with scrolling, but with the dropdown lists resetting when the crafting job is updated; which seems like a different problem.
