### ISSUE TITLE
Enhancements to terminals

### ISSUE THREAD

**Issue by goreae** [CyclopsMC/IntegratedTerminals#39]
I was asked for my gripes with the terminals on discord and was told to post them on github so here we go

- [x] Terminals have a habit of forgetting your sorting settings. They'll reset sorting and JEI preferences and that's really annoying. Also mentioned in #28 

- [ ] Putting items into the terminal is funny. It doesn't behave like a normal inventory, so you can't insert swaths of items using mouse tweaks or inventory tweaks features. You're left to insert them one stack at a time. If you try, one stack might go into the system, but the rest will either go into the crafting grid (even if you're on the storage tab) or act like there isn't an inventory at all. Maybe behind the scenes the terminal could have a small internal buffer of its own that you put items into, then it distributes said items to the appropriate locations. Said buffer would also be visible by the system so you still have access while they're in flux. Just a thought.

- [x] Shift-clicking items out of the terminal moves ALL of the items into your inventory. So if I have like fifty stacks of cobble and only need the one stack, I can't just shift click it into my inventory or my pockets will fill entirely with cobble. When I'm shift clicking items out of a terminal, I almost always just want the one stack not all the stacks.

- [x] The crafting grid clear button behavior should be reversed. Or at least there should be a button to reverse it. I very VERY rarely actually want the grid to empty into my inventory. For the main system, I would prefer the excess items just go into the system instead. It's mainly useful for items to pop into your inventory instead when you're using a terminal as a debug tool, like I did for my salt producer. Furthermore, when you have stuff in the crafting grid and you load up a new recipe, all of the items that were in the grid go into your inventory instead of the system.

- ~~[ ] When you right-click the search bar, it selects the text instead of just clearing it like you'd expect. Though this is probably an issue with integrated dynamics as a whole since I've had that happen with the logic programmer too. It's pretty much universal at this point that in minecraft, if you right-click a search bar, it clears it. Just selecting it seems like a weird half-step to that that serves no apparent purpose.~~

- [x] JEI only recognizes the system's inventory for auto-filling recipes. It does not recognize items in your own inventory.

**Comment by rubensworks** [comment]
Thanks for the suggestions! Will keep them in mind for future updates.

**Comment by rubensworks** [comment]
Moving the MouseTweaks part of this issue to #18
