### ISSUE TITLE
Some Shenaningans

### ISSUE THREAD

**Issue by Fortist** [CyclopsMC/IntegratedTerminals#4]
Sometimes, shift clicking items while in the terminal makes it go into the crafting grid on the crafting tab

Is the terminal meant to have this slowish lag to it? ergo, I pull an item out and a second later it is removed. 
Is there something I can change to make it not?

**Comment by rubensworks** [comment]
> Sometimes, shift clicking items while in the terminal makes it go into the crafting grid on the crafting tab

That's not normal. Could you report this as a bug?

> Is the terminal meant to have this slowish lag to it? ergo, I pull an item out and a second later it is removed. Is there something I can change to make it not?

This sounds like a caching issue (the thing that makes it _not_ lag while the terminal is not being used). I thought I had added something to make the cache invalidate immediately when interacting via the terminal. Could you open a separate bug report for this as well?
