### ISSUE TITLE
Dupe stackable item

### ISSUE THREAD

**Issue by CKATEPTb** [CyclopsMC/IntegratedTerminals#40]
- :bug: Bug
### Dupe stackable item
**How to do it?**
https://media.giphy.com/media/kaNEErcd8RaStFJgmB/giphy.gif
**Tested on:**
- Forge: 1.12.2-2838 - https://github.com/MinecraftForge/MinecraftForge/tree/1.12.x
- Spongepowered 1.12.2-2838 API7 - https://github.com/SpongePowered/SpongeForge
- Tablecloth 1.12.2-2838 - https://gitlab.com/bending/tablecloth/tablecloth

**Comment by mark-sheremeta** [comment]
I have the same problem

**Comment by rubensworks** [comment]
@CKATEPTb Can you include your ITerminals/IDynamics/CyclopsCore/CommonCapabilities versions?

**Comment by CKATEPTb** [comment]
ITerminals - 1.0.9
IDynamics - 1.0.17
CyclopsCore - 1.4.0
CommonCapabilities - 2.4.4
@rubensworks

**Comment by rubensworks** [comment]
Thanks! Those are the latest versions, so something is definitely not working like it should...

**Comment by CKATEPTb** [comment]
> Thanks! Those are the latest versions, so something is definitely not working like it should...

How soon will the fix be? I hope it's be fixed out of turn? This makes it difficult to put the mod on the server.

**Comment by CKATEPTb** [comment]
A temporary fix can be found here [GITLAB](https://gitlab.com/bending/tablecloth/integratedterminals/commit/0ae5d9345c5e3a897fcb219c0cc8f8d39c5f5d5e#8f277cc82bac22bcc243b84cef6fa8ab20d566c9_168_163)
