### ISSUE TITLE
The storage terminal can destroy items dropped into the crafting output slot

### ISSUE THREAD

**Issue by Adirelle** [CyclopsMC/IntegratedTerminals#41]
#### Issue type:

- :bug: Bug

____

#### Short description:

When the crafting grid is empty, dropping items on the output slot of the crafting terminal destroys them.

#### Steps to reproduce the problem:

1. Plug together a chest, a cable, an item interface and a storage terminal, so you can access the content of the chest through the terminal.
2. Put some items in the chest.
3. Using the terminal, select the crafting tab, and as the crafting grid is empty (no recipe), take some of the items from the network and drop them on the crafting *output* slot.

#### Expected behaviour:

We should be able to drop items into the output slot of the crafting tab. Moreover, they should never disappear.

____

#### Versions:

- This mod: 1.12.2-1.0.9
- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Integrated Dynamics : 1.12.2-1.0.18
- Integrated Tunnels : 1.12.2-1.6.10
- CyclopsCore: 1.12.2-1.5.0
- CommonCapabilities : 1.12.2-2.4.4

I checked the bug with only these mods installed.

**Comment by rubensworks** [comment]
Ouch, that's not good, thanks for reporting.
