### ISSUE TITLE
Issue with GregTech CE

### ISSUE THREAD

**Issue by MasterEnderman** [CyclopsMC/IntegratedTerminals#43]
#### Issue type:

- :bug: Bug

____

#### Short description:

Most Blocks from the GregTech Community Edition are invisible when viewed from the terminal.

![image](https://user-images.githubusercontent.com/24524662/65332501-1dff0700-dbbf-11e9-88fa-3e2b8626a475.png)

#### Steps to reproduce the problem:

1. place down chest
2. put blocks from GregTech CE inside the chest
3. connect a terminal to the chest
4. open the terminal

#### Expected behaviour:

all blocks are shown 
____

#### Versions:

- This mod: 1.0.10
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- GregTech CE: 1.8.8.440

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
