### ISSUE TITLE
Server crash with un-configured Crafting Terminal

### ISSUE THREAD

**Issue by happybandit360** [CyclopsMC/IntegratedTerminals#44]
#### Issue type:

- :bug: Bug

____

#### Short description:

When attempting to access the Crafting Terminal, it caused a server crash. 

#### Steps to reproduce the problem:

1. Item Interface attached to Copper Colossal Chest Interface
2. Logic cable run 3-4 blocks out
3. Crafting Terminal attached to cable
4. Right click on CT brings up GUI, but crashes server

Note: This crash occurred twice on stream (can provide link, if desired), but was not reproduceable in single player

#### Expected behaviour:

Expected behavior was to open Crafting Terminal without issue. We know now that because there was no Storage Terminal attached to the system, it wouldn't have done anything, but we did not expect it to crash the server.
____

#### Versions:

- This mod: 1.12.2-1.0.11
- Minecraft: 1.12.2
- Forge: 14.25.5.2838

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
