### ISSUE TITLE
Client Crash When Viewing Crafting Terminal When Subjob Completes

### ISSUE THREAD

**Issue by Trainerredstone7** [CyclopsMC/IntegratedTerminals#45]
#### Issue type:

- :bug: Bug

____

#### Short description:

When viewing the progression of a complicated crafting job in the Crafting Terminal, the client sometimes crashes when one of the subjobs completes.

#### Steps to reproduce the problem:
I'm not sure if the issue is 100% reproducible, but I know that it did happen when crafting Actually Additions Phantomfaces from scratch (crash happened when the subjob for Diamatine Crystals finished).

1. Set up a network that autocrafts an item that requires additional components to be crafted.
2. Request an autocraft for the item (it may be possible that the bug only appears when more than one of the item is requested).
3. View a Crafting Terminal on the network while the craft is in progress, and view the details for that specific crafting job.
4. The crash may occur when one of the subjobs for the crafting job completes.

#### Expected behaviour:

The client shouldn't crash when a subjob completes.

____

#### Versions:

- This mod: 1.12.2-1.0.10, also Integrated Crafting is 1.12.2.-1.0.8, Integrated Tunnels is 1.12-1.6.10, Integrated Dynamics is 1.12.2-1.1.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Log file:

https://pastebin.com/zyDMS42y

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
