### ISSUE TITLE
Railcraft Creosote Bottles vs. Storage Terminal

### ISSUE THREAD

**Issue by TomyLobo** [CyclopsMC/IntegratedTerminals#46]
#### Issue type:

- :bug: Bug

____

#### Short description:

Railcraft Creosote Bottles are magically transformed into whatever fits into your fluid storage when shift-clicking them into the storage terminal's fluid tab. I tried this with a max-upgraded metal drum from "Barrels, Drums, Storage & More"
Also, if I click Creosote Oil fluid and then click an empty bottle, it takes 100 buckets of Creosote Oil out instead of 1.
Picking up an empty or filled bottle and clicking it into the terminal works as expected (i.e. transfers only 1)

I'd assume the same issue arises with Railcraft's other bottle, the Steam Bottle.

#### Steps to reproduce the problem:

1. Place a Metal Drum (might work with other storages, too)
2. Upgrade the Metal Drum using an Upgrade: Capacity x64
3. Place a Fluid Interface on the Metal Drum
4. Place a Logic Cable on the Fluid Interface
5. Place a Storage Terminal on the Logic Cable
6. Get a single Creosote Bottle
7. Open the Storage Terminal
8. Switch to the Fluid Storage tab
9. Shift-click the Creosote Bottle
     - Expected: Metal Drum now contains 1 bucket of Creosote Oil
     - Actual: Metal Drum now contains 128 buckets of Creosote Oil
10. If the Metal Drum isn't full, fill it to 128 buckets
11. Click the Creosote Oil
12. Click the Glass Bottle
     - Expected: Metal Drum now contains 127 bucket of Creosote Oil
     - Actual: Metal Drum now contains 28 buckets of Creosote Oil

#### Expected behaviour:

I expect Creosote Bottles to be worth exactly 1 bucket of Creosote Oil.
Not 100 and certainly not between 32768 and infinity :)
____

#### Versions:

- This mod: 1.0.11
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

Other related mods:
```
$ md5sum {Integrated,Barrels,railcraft}*.jar
c1aff93e2ddcedda892e338dd1cc0950 *IntegratedCrafting-1.12.2-1.0.8.jar
82b15eaa0c2b4421408db074ff464374 *IntegratedDynamics-1.12.2-1.1.0.jar
66f8eef05a5347180992a58adcc3e878 *IntegratedTerminals-1.12.2-1.0.11.jar
4dcb9b2079097ca6ae15cd723f071f94 *IntegratedTunnels-1.12.2-1.6.10.jar
948d49b065fd9f07cc046111d93b0700 *BarrelsDrumsStorageAndMore-0.0.24.jar
b6f0592e8f5c24d07fe065f1c97c8fda *railcraft-12.0.0.jar
```

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by TomyLobo** [comment]
If you need another external item for comparison, the Tome of Knowledge from Thermal Foundation doesn't seem to have this issue.

**Comment by rubensworks** [comment]
Seems to be caused by RailCraft, reported at https://github.com/Railcraft/Railcraft/issues/1893
