### ISSUE TITLE
Add a machine to detect items in the terminal

### ISSUE THREAD

**Issue by Gan-N** [CyclopsMC/IntegratedTerminals#49]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

    All kinds of things will be put in the box. When I check the storage terminals, although the items show the total number, they are not necessarily all in one box. This makes it impossible for me to simply know the total number of some of my projects to specify the production plan.

This machine can:
1. Detect the number of items in the storage terminal according to the variable card list
2. Output items to a channel or pipe based on the detected quantity

**Comment by rubensworks** [comment]
I'm sorry, but I have a really hard time understanding your issues...

Detection of items in the network would be something you typically do using Integrated Dynamics/Tunnels.
