### ISSUE TITLE
Auto-fill crafting grid with full stack and send back items to the network directly when calling a new recipe

### ISSUE THREAD

**Issue by WillisShek** [CyclopsMC/IntegratedTerminals#51]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

- **Auto-fill crafting grid will full stack of items if those items already exist in the system, and only refill the items if there is none of them instead of refilling them every time.**
It allows a faster crafting process as it requests lesser requests from the system, as the crafting is a bit slow when crafting a large amount due to the need of pulling necessary items every time an item is crafted. If possible, caching the recipe like what [FastWorkbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench) did can help as well.
Some mods like [Simple Storage Network](https://www.curseforge.com/minecraft/mc-mods/simple-storage-network) and Crafting Station from [Tinkers Construct](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct) are able to mimic the vanilla crafting table, and thus able to use what FastWorkbench provides to speed up the crafting speed. Maybe they can be a good reference.

- **Send back items to the network on default when calling a new recipe from JEI.**
I found that most of the time items are pulled from the network instead of player inventory, so it would make more sense that those items should be back to the network on default. It will be great if it is configurable by either mob config or GUI.
_Related to #39_ 

Thanks for the great mod. Finally, I can get rid of the bits based storage system like AE and RS.

**Comment by rubensworks** [comment]
> Send back items to the network on default when calling a new recipe from JEI.

Seems to be the case already. I probably implemented this some while ago.
