### ISSUE TITLE
crash when viewing crafting job terminal during a crafting process (and i don't really know what else)

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedTerminals#53]
#### Issue type:

- :bug: Bug

____

#### Short description:

i have crashed like 3 times now because i was looking at the crafting job terminal when an item was crafting. i don't know why it happened, so i can't provide steps. all i have is a crash log.

#### Versions:

- This mod: 1.0.13
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

#### Log file:
[link](https://pastebin.com/2XBtBN2b)

**Comment by rubensworks** [comment]
Thanks for reporting!
