### ISSUE TITLE
Server crash on terminal interaction

### ISSUE THREAD

**Issue by RonanRaven** [CyclopsMC/IntegratedTerminals#57]
#### Issue type:
- :bug: Bug

____
#### Short description:
Server crash on terminal interaction

#### Steps to reproduce the problem:
Start a forge server for a client with the same forge version and the same mods (Integrated Terminals only)
Connect to server
place one cable down
place terminal onto cable
interact with terminal

Observed: server crash

#### Expected behaviour:
Interactions should work on server as they do in single player

____
#### Versions:
- This mod: IntegratedTerminals-1.15.2-1.0.14.jar
- Minecraft: 1.15.2
- Forge: forge-31.2.36

#### Log file:
https://pastebin.com/xfa0cfAE

**Comment by rubensworks** [comment]
Thanks for reporting!
