### ISSUE TITLE
Crafting Job terminal is uncraftable [1.15]

### ISSUE THREAD

**Issue by KrAzYGEEK32** [CyclopsMC/IntegratedTerminals#58]
#### Issue type:

- :bug: Bug

____

#### Short description:

seems like crafting job terminal is uncraftable in 1.15, both the terminal recipes seem to craft only the storage terminal
![2020-09-16_20 11 32](https://user-images.githubusercontent.com/59537798/93353277-5af4ec80-f859-11ea-8757-f5fe9f4ae54e.png)
![2020-09-16_20 11 38](https://user-images.githubusercontent.com/59537798/93353299-62b49100-f859-11ea-8df7-92fafb73f6ed.png)

#### Steps to reproduce the problem:

1. N/A

#### Expected behaviour:

a recipe for crafting job terminal

____

#### Versions:

- This mod: 1.0.15
- Minecraft: 1.15.2
- Forge: 31.2.36

**Comment by rubensworks** [comment]
Thanks for reporting!
