### ISSUE TITLE
[1.15.2] Server crash when clicking a recipe from JEI into crafting tab of storage terminal

### ISSUE THREAD

**Issue by CplPibald** [CyclopsMC/IntegratedTerminals#59]
#### Issue type:
- :bug: Bug

____

#### Short description:

Server crash when clicking a recipe from JEI into crafting tab of storage terminal

```
java.lang.NoSuchMethodError: net.minecraft.network.PacketBuffer.func_218666_n()Ljava/lang/String;
        at org.cyclops.cyclopscore.network.PacketCodec$9.decode(PacketCodec.java:189) ~[?:1.8.4] {re:classloading}
        at org.cyclops.cyclopscore.network.PacketCodec.lambda$decode$1(PacketCodec.java:502) ~[?:1.8.4] {re:classloading}
```

#### Steps to reproduce the problem:

InDy network containing only a storage terminal and item interfaces.  In the specific example, network had two item interfaces connected to a StorageDrawer controller, and to a colossal chest.  Was able to browse, send, and receive items from both inventories.

In storage terminal, switch to crafting grid tab.  Open JEI and view crafting recipes for any item.  Click on the small '+' icon in JEI recipe view to transfer recipe to crafting grid.

1. ...

#### Expected behaviour:

Recipe ingredients are populated into crafting grid from storage or player inventory

____

#### Versions:
forge-1.15.2-31.2.37
CyclopsCore-1.15.2-1.8.4
IntegratedDynamics-1.15.2-1.1.17
IntegratedTunnels-1.15.2-1.6.14
IntegratedTerminals-1.15.2-1.0.15

#### Log file:

https://gist.github.com/CplPibald/dcfaf84179e4c9e0690c1079b3dcaf46

**Comment by rubensworks** [comment]
Thanks for reporting!

Looks like a client-only method that is being called server-side.
