### ISSUE TITLE
Unable to Scroll Down in Storage Terminal

### ISSUE THREAD

**Issue by HipHopHuman** [CyclopsMC/IntegratedTerminals#60]
#### Issue type:

- :bug: Bug

____

#### Short description:

The player is unable to scroll down when viewing the Storage Terminal GUI. This appears to be consistent across all the different tabs.

#### Steps to reproduce the problem:

1. Install Minecraft 1.15.2
2. Install Forge
3. Install Integrated Dynamics
4. Install Integrated Tunnels
5. Install Integrated Terminals
6. Start the game
7. Start a creative world
8. Add Logic Cable, Item Interfaces, Chests and a Storage Terminal to your hotbar
9. Build a network with around 6 chests worth of storage space
10. Add enough items to the network so that you have to scroll down to browse the items
11. Attempt to scroll down

#### Expected behaviour:

I expect that the scrollbar will scroll down, allowing me to access the items below the critical viewport. Instead, the scrollbar remains fixed, and I have to explicitly search for items to access them.

____

#### Versions:

- This mod: 1.0.15
- Minecraft: 1.15.2
- Forge: 31.2.41

#### Log file:

I will provide this if requested

**Comment by rubensworks** [comment]
Thanks for reporting!
