### ISSUE TITLE
3x3 Crafting input items not consumed if holding an item transfer request item

### ISSUE THREAD

**Issue by VT-14** [CyclopsMC/IntegratedTerminals#65]
#### Issue type:

- :bug: Bug

____

#### Short description:

In the Storage Terminal's Crafting Page; If you are holding an item transfer request 'item', then crafting something using the built in crafting grid will cancel the item transfer request (just not move it anywhere), and give you the resulting item from the crafting recipe, but not consume the recipe's input items.

Additionally, with my normal display settings the ? button for JEI's auto-fill happens to be over the Terminal's inventory, and I automatically pick one of those transfer request items up almost every time I go to craft something from JEI, making this effective dupe bug really easy to do by accident.

#### Steps to reproduce the problem:

1. On a Storage Terminal's Crafting Page, set a recipe.
2. Pick up anything from the Storage Terminal's storage area to start an item transfer request.  Do *not* put it in your inventory.
3. While holding that transfer request item, attempt to pick up the crafting output item.
4. Observe the transfer request item remain in the Terminal's storage area, you are now holding the recipe's output item as a normal item, and the recipe inputs are still in the Terminal's crafting grid.

Video Demo: https://youtu.be/Y5zp6AbWB98

#### Expected behaviour:

* Item transfer request to cancel (not move the items)
* The crafted item gets crafted with the input items being consumed.

* Pressing the ? button in JEI to not create a transfer request (different but somewhat related bug).

____

#### Versions:

- This mod: IntegratedTerminals-1.16.4-1.1.1
- Minecraft: 1.16.5
- Forge: 36.0.14

- IntegratedTunnels-1.16.4-1.6.16
- CyclopsCore-1.16.4-1.11.1
- IntegratedDynamics-1.16.4-1.4.3

#### Log file:

Debug Crash: https://gist.github.com/VT-14/36169828b50623f2f94a0a8d6ef549e8
latest.log: https://gist.github.com/VT-14/6e53f1b0d81a16b624f694d107923185

**Comment by rubensworks** [comment]
Thanks for reporting!
