### ISSUE TITLE
Subjective Terminal UX Improvements

### ISSUE THREAD

**Issue by Bluberry-Kat** [CyclopsMC/IntegratedTerminals#66]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:
Hi. :wave: 
I've been playing modded minecraft for a very long time, so whenever I find a networked-storage mod that I can engage with, that's something to be applauded. Good job for that.
I'd like to make Integrated Terminals my daily driver, but there are a couple of features I need for this to be a reality. 
##### Per-Terminal Settings:
Right now, settings seem to naively be applied to every terminal placed in-world.  
Personally, I treat my terminal differently based on what it's being used for.  
For example, at home I would prefer to be in the Crafting tab, and for the search-bar to be auto-focused when I open it.  
When I'm at a mob farm, this wouldn't be helpful to me, as the terminal isn't being used for crafting. I would probably have JEI sync on (because you can quick-focus the search bar via ctrl+f) so that I could search for items via enchantment.  

Being able to configure terminals individually, instead of as a group, would improve this for me. No set of settings will work for every use-case, so allow more variability! 

* [X] TODO

##### Default Settings for Terminals:

Somewhat related to #28, which I'm sure you're loathe of being reminded of at this point, but with a slightly bigger scope.  
With Per-Terminal Settings in-mind, it would be more appropriate to have a "default setting" that a terminal is set to when placed.  
As per configuring these defaults, I'm just thinking a set-default button on the GUI somewhere, and it'll copy the defaults for every pane currently available on the terminal.

* [x] TODO

##### Simplified Search Bar:
To preface this, I understand why the search bars are how they are right now.  
It's a useful feature. It just happens to conflict with my workflow.  
Right now, if I change tabs (which I frequently do, the storage tab is much better for searching items than the crafting tab), whatever I was searching on the one tab is still on that tab, and not the newly-focused one.  
I'm aware this is a feature, and not a bug. So here's what I'm asking:  
I want a setting that changes the search bar, so that instead of each tab having its own text field, each bar shares the same text, no matter what.

* [x] TODO

##### JEI-sync tweaks:
This is really more of a bug than a feature request. I should move it out into its own issue, but while I'm here:  
With JEI-Sync enabled, if I switch my current tab, I have to focus the JEI search bar again for it to sync with the terminal's bar.
I think it would be more appropriate if the sync occurred when you changed tabs.

* [x] TODO

##### Crafting Settings:
Infrequently do I ever want to craft an entire stack of something. There are situations when I do, such as compressing ingots into blocks, but I'm sure every modded player has accidentally crafted 64 Thermal Expansion Redstone Furnaces by accident at least once.  
In-tandem with per-terminal settings, it would be nice to configure how many items you shift-click out of the crafting-results slot at once. I'd probably just set it to 1.

* [x] TODO

##### Conclusion:
I let this get longer than I wanted! If this is a problem, let me know and I'll split these into their own individual issues.
Thank you for your hard work. :heart:

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
This issue overlaps a bit with #28 and #39.

I'm glad to see a detailed issue like this. Many people have complained about ITerms usability, but few people actually told me exactly what the problems are they are experiencing. So thanks for taking the effort for writing this out :-)

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by Bluberry-Kat** [comment]
> I'm glad to see a detailed issue like this. Many people have complained about ITerms usability, but few people actually told me exactly what the problems are they are experiencing. So thanks for taking the effort for writing this out :-)  

I'm happy to see a positive response. Excited to see if anything comes out of this.
