### ISSUE TITLE
Crash when opening Terminal

### ISSUE THREAD

**Issue by ZeekDaGeek** [CyclopsMC/IntegratedTerminals#67]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Whenever I right click on the Integrated Terminal after upgrading to 1.2.0 it causes the game to crash. If I downgrade to 1.1.3 it seems to work fine.

#### Steps to reproduce the problem:

1. Upgrade to 1.2.0
2. Right click on Terminal.
3. Enjoy the crash.

#### Expected behaviour:

____

#### Versions:

- This mod: IntegratedTerminals-1.16.5-1.2.0
- Minecraft: 1.16.5
- Forge: 36.1.2

#### Log file:

It seems like it might be related to JEI Integration: https://gist.github.com/ZeekDaGeek/3677c04862d3cecb709ba063552a31d9

Screenshot of setup:
![FDJrh](https://user-images.githubusercontent.com/1709288/113343260-d21d3a00-92ec-11eb-9199-eccbb8974f08.png)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by HanzMantis** [comment]
I just wanted to +1 this as well. Here's the crash log from my world: https://paste.ee/p/5mDne

<blockquote><img src="https://paste.ee/img/icon.png" width="48" align="right"><div>Paste.ee</div><div><strong><a href="https://paste.ee/p/5mDne">View Paste 5mDne</a></strong></div><div>Paste.ee - View Paste 5mDne</div></blockquote>
