### ISSUE TITLE
Terminals Won't work

### ISSUE THREAD

**Issue by RGFTheCoder** [CyclopsMC/IntegratedTerminals#69]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Terminals randomly won't work

#### Steps to reproduce the problem:

1. ?????

#### Expected behaviour:
Terminals always allow removal of items

____

#### Versions:

- This mod: 1.2.1
- Minecraft: 1.16.5
- Forge: 36.1.0

#### Log file:

https://pastebin.com/fTgwFbrN

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> ?????

Is there really nothing more you can say about this?
It will be impossible for me to debug otherwise.

**Comment by RGFTheCoder** [comment]
I really don't know why it happens, but it occasionally just stops and I have to replace it; happens with other parts as well, but I saw this logging an error message

**Comment by rubensworks** [comment]
What do you mean with "just stops"?
Does the part not open? Does it open, but nothing is shown?

> happens with other parts as well

Do you mean other types of parts? Or always just storage terminals? If it happens with one part, does it also happens with all other parts on the network? Does this also occur with the portable storage terminal?

**Comment by RGFTheCoder** [comment]
it opens, but I cant put in items or remove them, and "other types of parts" refers to things like the item interfaces from IntegratedTunnels, where the crafting system pretends like the items dont exist, and I have to replace the interfaces

**Comment by rubensworks** [comment]
Can you try reproducing without any other mods installed? Might be another mod messing with things.
