### ISSUE TITLE
Storage Terminal hangs when crafting

### ISSUE THREAD

**Issue by Unbox101** [CyclopsMC/IntegratedTerminals#7]
#### Issue type:

- :bug: Bug

____

#### Short description:

When attempting to auto craft a display panel from integrated dynamics inside of a storage terminal  the terminal would hang at the crafting plan screen showing the message "Calculating crafting plan..." and would never craft the item.

#### Steps to reproduce the problem:

I was able to reproduce this bug in a fresh instance of minecraft and a fresh world.
I built a storage terminal and connected it to a chest.
I placed a crafting table with a crafting interface on top of it and connected it to the network.
I then made all the recipe cards that are required to craft a display screen and put them into the crafting interface.
I filled the chest with everything it needed to craft a display screen.
When I tried to autocraft a display screen from the storage terminal it hung at the crafting plan menu.
So far I've seen this happen with the display panel and the storage terminal when trying to autocraft them.

Note: If you don't have the required items to craft the display panel then the crafting plan screen works normally and shows you what you are missing.

#### Expected behaviour:

What normally happens with other recipes is it shows that it has all of the components to craft the item and then you can press the craft button to craft it. If it does not have all the components to craft the item then it shows you what you are missing so you can add it to the network and then try again.

____

#### Versions:

- This mod: 1.0.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by rubensworks** [comment]
What version of Integrated Crafting are you using? This should have been fixed in version 1.0.1.

**Comment by Unbox101** [comment]
Integrated Crafting is Version 1.0.0
That was my mistake. I didn't see the new update.

Just updated and everything seems to be working perfectly.

**Comment by rubensworks** [comment]
No worries :-)
