### ISSUE TITLE
Mr crayfish's gun mod's guns can't be taken out of the terminal

### ISSUE THREAD

**Issue by GaN8373** [CyclopsMC/IntegratedTerminals#70]
#### Issue type:

- :question: Question 

____

#### Question:

Mr crayfish's gun mod's guns can't be taken out of the terminal
![image](https://user-images.githubusercontent.com/80253667/115851308-60528f00-a459-11eb-8eba-312a38d15a1b.png)
MOD Version：
IntegratedTerminals-1.16.5-1.2.2
IntegratedDynamics-1.16.5-1.7.2
cgm-1.0.1-1.16.3（https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod）

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by GaN8373** [comment]
> Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

thank，It's just a little bit of a hassle

**Comment by rubensworks** [comment]
Seems to be working fine on my end.

**Comment by GaN8373** [comment]
> Seems to be working fine on my end.

There is no ammunition in the gun. If it is full, it can be taken out

**Comment by rubensworks** [comment]
Still works fine even then on my end.
Please let me know if you can reproduce the issue with no other mods (other than those related to this issue) are installed.

**Comment by GaN8373** [comment]
> Still works fine even then on my end.
> Please let me know if you can reproduce the issue with no other mods (other than those related to this issue) are installed.

I will delete my modpack and try other mods again. If it reappears, I will reply to you again. thank
