### ISSUE TITLE
Portable Storage Terminal should be locked in place while open

### ISSUE THREAD

**Issue by Chewypuppielover** [CyclopsMC/IntegratedTerminals#75]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem: The Portable Storage Terminal should be locked in place while open

1. Open the Portable Storage Terminal connected to a network
2. Be on the crafting tab
3. Shift click the terminal
4. Watch sadly as it trys to put itself into the grid at the same time closing because you no longer have the item
5. Also realize that the grid is a separate inventory and that particular grid can never be accessed again to retrieve your terminal

#### Expected behaviour:

The Portable Storage Terminal should be locked in place while open, so that trying to move it in any way doesn't work.

#### Versions:

- This mod: 1.2.10
- Minecraft: 1.16
- Forge: 36.2.9

**Comment by rubensworks** [comment]
Thanks for reporting!
