### ISSUE TITLE
Shift-click crafting deletes a set of items (1.18.1-1.2.11)

### ISSUE THREAD

**Issue by ZenDev20** [CyclopsMC/IntegratedTerminals#76]
#### Issue type:
- :bug: Bug 
____

#### Short description:
Shift click to craft more than one item at a time will give you one item, clears the crafting grid, and voids one set of ingredients.

Example: Crafting a brick block will consume 8 bricks, give one block, and clears the crafting grid.

Setup: chest with a stack of bricks (item) connected with an item interface to a storage terminal.

Note: auto-crafting works as intended and doesn't have the same issue.

#### Versions:
- Minecraft: 1.18.1
- Forge: 39.0.59
- Integrated Terminals: 1.2.11

#### Other Mods Installed
- Integrated Tunnels: 1.8.9
- Integrated Dynamics: 1.10.6
- Integrated Crafting: 1.0.20
- Cyclops Core: 1.13.0
- Common Capabilities: 2.8.1

**Comment by rubensworks** [comment]
Thanks for reporting!
