### ISSUE TITLE
Large server hang when shift click crafting in storage terminal grid

### ISSUE THREAD

**Issue by theboo** [CyclopsMC/IntegratedTerminals#78]
#### Issue type:

- :snail: Performance issue 

____

#### Short description:

Any time i shift click craft stacks out of the storage terminal, the server hangs until the crafting has completed, happens both on a server and in SP. Seems very similar to issue #48 

#### Steps to reproduce the problem:

1.Install a larger pack with lots of recipes(enigmatics 6 v0.5.26 used here, but also tested in ATM6 v1.8.20)
2. Make a small storage network
3.  Shift click craft a stack of anything
____

#### Versions:

- This mod: 
![image](https://user-images.githubusercontent.com/3585761/155862221-94d5ef82-48ef-4289-9e4b-8fa22eca58da.png)

- Minecraft: 1.16.5
- Forge: 36.2.29

#### Profiler output:

https://spark.lucko.me/yTddKGNVRr

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by theboo** [comment]
As a side note, ive noticed that it is not crafting the whole stack at a time as was mentioned in issue #51 , as you can see in the gif below, it sloooooowly crafts the full stack(you can see the server hanging in the background with the flashing sky). I dont know if this is related to the server hang or not, but i expect it is. In a world with just IT/ID and dependencies(so much less recipes/tags) it is much faster but still one item at a time. Changing the below config between true and false seems to not affect anything.
![image](https://user-images.githubusercontent.com/3585761/155862626-b4de3040-2206-4226-a736-369d14342377.png)

https://gyazo.com/646e50f7cc0b66948d21a7ea2b894fc9


<blockquote><img src="https://i.gyazo.com/thumb/1200/646e50f7cc0b66948d21a7ea2b894fc9-gif.gif" width="48" align="right"><div><img src="//assets2.gyazo.com/favicon.ico" height="14"> Gyazo</div><div><strong><a href="https://gyazo.com/646e50f7cc0b66948d21a7ea2b894fc9">Gyazo</a></strong></div><div>&nbsp;</div></blockquote>

**Comment by rubensworks** [comment]
Profile screenshot for reference: <img width="1157" alt="Screenshot 2022-02-28 at 08 28 18" src="https://user-images.githubusercontent.com/440384/155941731-04c2e859-b838-435b-9bb4-871ea21877ae.png">

**Comment by rubensworks** [comment]
So apparently this was fixed in the 1.12, but the fix somehow got lost for the 1.16 update. Will be fixed in next release.

**Comment by theboo** [comment]
amazing, thanks!

**Comment by theboo** [comment]
just tested the new version, same craft that took 30+seconds of tick time in a 50 second profile took less than 1 second of tick time in the same 50 second profile. Shift click stacks craft almost instantly now. perfect! thanks again!
