### ISSUE TITLE
better item extracting

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedTerminals#8]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

1: pressing the mouse wheel multiple times should take more of that item out of the storage, instead of just putting it in and out
2: scrolling the mouse wheel should allow you to select a specific amount to take (scroll down should "select" more of that item to transfer and scroll up should "unselect" more of said item)
3:shift+middle click should take 1 of the selected item directly into/out of the selected inventory each time.

**Comment by rubensworks** [comment]
1 should be possible to do, but 2 probably not, since the mouse wheel is tied to the scrollbar.
