### ISSUE TITLE
The game crashed whilst rendering overlay Error: java.lang.RuntimeException: null

### ISSUE THREAD

**Issue by MickeyMouseYT** [CyclopsMC/IntegratedTerminals#82]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The game crashed whilst rendering overlay
Error: java.lang.RuntimeException: null

#### Versions:

- This mod: 1.2.13 
- Minecraft: 1.16.5
- Forge: 32.2.35

#### Log file:

https://pastebin.com/bFrnZqDP

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This doesn't appear to be a bug caused by this mod.
It looks like _all_ registrations by all mods fail apparently.

I guess there is a mod in your pack that is horribly breaking things, but no idea how, as I've never seen anything like this before.

**Comment by MickeyMouseYT** [comment]
> This doesn't appear to be a bug caused by this mod. It looks like _all_ registrations by all mods fail apparently.
> 
> I guess there is a mod in your pack that is horribly breaking things, but no idea how, as I've never seen anything like this before.

What a mod ?
