### ISSUE TITLE
Item Exporter Not Requesting Crafts with Pre-requesites

### ISSUE THREAD

**Issue by bangplaysgames** [CyclopsMC/IntegratedTerminals#85]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The Item Exporters will not request crafts of pre-requisite ingredients for their export items. 

#### Steps to reproduce the problem:

1.  Provide recipes for end result item to export as well as all the crafted ingredients. 

2.  Provide raw materials to appropriate inventories. 

3.  Export the item in an item exporter with crafting option checked. 

#### Expected behaviour:

Item exporter will queue all necessary known crafts required to export the final resulting item. 

____

#### Versions:

- This mod:  1.11.8
- Minecraft:  1.18.2
- Forge:  40.1.17

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you provide a minimal reproducible example, using only ID+vanilla?

**Comment by bangplaysgames** [comment]
Seems to not happen with only the ID suite installed.

**Comment by rubensworks** [comment]
Could you check which mod is causing the problem?
We may have to report the issue on another issue tracker in that case.

**Comment by bangplaysgames** [comment]
It's difficult to narrow down which mod might be causing this, as the pack it's in (TNP Limitless 5) has about 300 mods.  I can confirm, however, that if the pre-requisite crafts aren't necessary, it queues the job for the final craft on export as intended.  If the pre-requisite crafts are necessary, however, it won't even attempt to craft anything.

**Comment by rubensworks** [comment]
There's not much I can do about this issue without any more details unfortunately.

In case you would obtain more details on a reproducible setup or specific mods that cause issues, please let me know, and we can re-open this issue.
