### ISSUE TITLE
 [Crash]: Clicking on Integrated Terminals energy w/ JEI installed: java.lang.IllegalArgumentException: Unknown ingredient class: class java.lang.Long

### ISSUE THREAD

**Issue by DasBrain** [CyclopsMC/IntegratedTerminals#86]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When clicking on the energy in a Storage Terminal, the client crashes.
Seems to be an issue with IntegratedTerminals + JEI

#### Steps to reproduce the problem:

1. Make an Integrated Dynamics Network with at least 1 Energy Battery + 1 Storage Terminal
2. Add some energy to to the Energy Battery
3. Open the Storage Terminal
4. Go to the Energy Tab
5. Click on the stored energy.
6. CRASH

#### Expected behaviour:

No crash?

____

#### Versions:

- This mod: IntegratedTerminals-1.18.2-1.3.0.jar              |IntegratedTerminals           |integratedterminals           |1.3.0               |DONE      |Manifest: NOSIGNATURE
- Minecraft: Minecraft Version: 1.18.2
- Forge: net.minecraftforge:40.1.73

#### Log file:

https://gist.github.com/DasBrain/9ce4776307c8cbc53ed099a4b592d776

Related bug: https://github.com/mezz/JustEnoughItems/issues/2988

**Comment by rubensworks** [comment]
Thanks for reporting!
