### ISSUE TITLE
A functioning Portable Storage Terminal in Crafting Mode can duplicate items when clearing the table to inventory

### ISSUE THREAD

**Issue by sctjkc01** [CyclopsMC/IntegratedTerminals#89]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Portable Storage Terminals linked to an Integrated Dynamics network and in the Crafting tab duplicates items when emptying the crafting grid to the player's inventory.  This is a re-report for #88, which was closed prematurely.

#### Steps to reproduce the problem:

1. Set up the network
  a. Attach a chest with an item interface
  b. Add on an Omni-Directional Connector
  c. Link a Portable Storage Terminal to that Connector
2. Open the Portable Storage Terminal and place any item into the crafting grid on the Crafting Tab
3. Use the Clear button while holding shift to dump the contents of the crafting grid to the player's inventory
4. Close the terminal and immediately re-open it

#### Expected behaviour:

The crafting grid continues to be empty

____

#### Versions:

Minecraft: 1.18.2
Forge: 40.1.74
Common Capabilities version 1.18.2-2.8.2
Cyclops Core version 1.18.2-1.16.0
**Integrated Terminals** version 1.18.2-1.3.2
Integrated Crafting version 1.18.2-1.0.25
Integrated Dynamics version 1.18.2-1.11.12
Integrated Tunnels version 1.18.2-1.8.15

#### Log file:

[none provided]

**Comment by rubensworks** [comment]
Thanks for reporting!
