### ISSUE TITLE
portable terminals

### ISSUE THREAD

**Issue by antrobot1234** [CyclopsMC/IntegratedTerminals#9]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

portable terminals. a short ranged one can be made with a terminal and a mono-directional connector and a long/multidimensional one with a omni-directional connector. they could be linked to a network via another omni/mono-directional connector on the network itself.

**Comment by rubensworks** [comment]
Ah yes, this has been on my private todo-list as well :-)
