### ISSUE TITLE
[Minor] Portable Storage Terminal only links when clicking the front of an Omni-Directional Connector

### ISSUE THREAD

**Issue by nskobelevs** [CyclopsMC/IntegratedTerminals#90]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I'm not sure if this is expected behaviour but the Portable Storage Terminal does not link to an Omni-Directional Connector if one is right clicking on the side of the connector and not the front face.

I initially thought the whole linking was broken as my connecters usually point upwards and I was right clicking the side when trying to link it.

#### Expected behaviour:

Maybe it should link regardless of which face you click on?

____

#### Versions:

- This mod: 1.4.0
- Minecraft:  1.19.2
- Forge: 43.1.30

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by nskobelevs** [comment]
> Thanks for reporting!

Seems this issue got incorrectly labeled as 1.18

**Comment by rubensworks** [comment]
That's intentional. It probably also exists in 1.18, since the code is almost identical.
