### ISSUE TITLE
Integrated Dynamics Storage Terminal Causing Server Crash on use

### ISSUE THREAD

**Issue by zediious** [CyclopsMC/IntegratedTerminals#92]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When interacting with an ID storage terminal, the server will crash almost immediately. The crash log is consistent each time this is performed.

#### Steps to reproduce the problem:

1. Place an ID Storage Terminal, connected to a simple network (interface and a chest were done in testing).
2. Open the terminal, experience consistent crash.

#### Expected behaviour:

I expect the terminal to open without crashing.
____

#### Versions:

- This mod: IntegratedTerminals-1.18.2-1.4.0
- Minecraft: 1.18.2
- Forge: 1.18.2-40.1.80

This issue occurs in All the Mods 7 - To the Sky, and the issue has also been reported on the modpack's tracker.

#### Log file:

 Server crash log: [https://gist.github.com/zediious/cc4abe676f003c4e8c224d3bde46b183](https://gist.github.com/zediious/cc4abe676f003c4e8c224d3bde46b183)

Making a guess, it appears as though Integrated Terminals is attempting to call client code, on the server. `java.lang.NoClassDefFoundError: net/minecraft/client/renderer/MultiBufferSource`
I can provide the server's actual log/debug, if that would provide more pertinent information than the crash log.

**Comment by rubensworks** [comment]
Thanks for reporting!
