### ISSUE TITLE
Crash on opening Crafting terminal/selecting category

### ISSUE THREAD

**Issue by Sar4h-3** [CyclopsMC/IntegratedTerminals#93]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Create a small network (interface with normal chest and crafting terminal)
2. Open the terminal. If its newly placed, selecting either storage or crafting will crash it, if it was already used once, just opening it will the same

#### Expected behaviour:

No crash 
____

#### Versions:

- This mod: 1.18.2-1.4.1
- Minecraft: 1.18.2
- Forge: 40.1.84

#### Log file:

[crash-2022-10-24_15.29.46-client.txt](https://github.com/CyclopsMC/IntegratedTerminals/files/9852100/crash-2022-10-24_15.29.46-client.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!
