### ISSUE TITLE
crafting from terminal adding recipe with + ultraz lag or freeze my game

### ISSUE THREAD

**Issue by Gayanfalor** [CyclopsMC/IntegratedTerminals#94]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I was doing some crafting in the terminal, but when i click on many recipe and clic on the + to add it i the crafting grid, my game is super laggy and almost crash. i asked to a friend to do it aswell an d for him its working fine, is there someting with my pc that mess the mod ?

![image](https://user-images.githubusercontent.com/10771109/203662979-e8aab34e-92fe-48d3-8538-7e27a47dd0a9.png)

#### Steps to reproduce the problem:

1. open your terminal
2. check for gauge mekanism recipe
3. clic the +
4. lag

#### Expected behaviour:

working as other recipe without mega lagg or freeze

____

#### Versions:

- This mod:  1.4.1
- Minecraft: 1.19.2
- Forge: 43.1.52

#### Log file:

https://paste.ee/p/0K7D8

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you share a profiling log as explain here? https://github.com/CyclopsMC/CyclopsCore/blob/master-1.18/.github/CONTRIBUTING.md#performance-issues-snail

<blockquote><img src="https://opengraph.githubassets.com/fc8d56f07b6bb9256cfa94ff9f2af2d52ece9d8c7f58ee6e519acdff59dc674a/CyclopsMC/CyclopsCore" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CyclopsCore">CyclopsCore/CONTRIBUTING.md at master-1.18 · CyclopsMC/CyclopsCore</a></strong></div><div>Minecraft library mod for EvilCraft, Integrated Dynamics and others. - CyclopsCore/CONTRIBUTING.md at master-1.18 · CyclopsMC/CyclopsCore</div></blockquote>

**Comment by Gayanfalor** [comment]
you mean with spark ? so i  e ned to launch it before clickingon the +?


got this one just start profiling before going into the terminal and clicking on the + and stopped it after the lag passed

https://spark.lucko.me/7kgzxyeEVs

**Comment by Gayanfalor** [comment]
Well, i got it too from a refined storage crafting grid, so it may comes from minecraft or something else, the hting is its not doing it when i do it with the  storage accessor from occltism.

Dont know whats  happenning in background after hitting the + but must be something weird ^^.
So its not from integrated dynamics as i got it too in Refined storage

**Comment by rubensworks** [comment]
Thanks!

Relevant part of the stacktrace for reference:
<img width="1238" alt="Screenshot 2022-12-06 at 15 08 33" src="https://user-images.githubusercontent.com/440384/205933935-0c5bec96-ded5-4137-84d1-6e922ab5e763.png">

**Comment by Gayanfalor** [comment]
that means ?
you got that from my spark ? so that problem was from ID or  refined have that problem too ?

**Comment by rubensworks** [comment]
It was an ID performance problem indeed. RS may have a similar problem.
