### ISSUE TITLE
Crafting job terminal doesn't render the "Cancel all jobs" button, but it is definitely there

### ISSUE THREAD

**Issue by Jack-McKalling** [CyclopsMC/IntegratedTerminals#95]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When you open the crafting job terminal, it appears that there is no "cancel all jobs" button. But if you click the area where the button is supposed to be, it does actually work.

Almost as if the button behaves like you applied the CSS `visibility:hidden` on it (for some reason) but left its click event in tact.

#### Steps to reproduce the problem:

1. Place a cable
2. Attach a Crafting Job Terminal
3. Open the terminal
    ❌ Notice there appears to be no button at the bottom
4. Click the center area at the bottom edge of the GUI
    ✅ The GUI successfully closes (and if there were jobs, they get cancelled)

![integrated crafting jobs](https://user-images.githubusercontent.com/14236702/204130971-9862c9f5-e9d3-47d4-b0b1-22cd9b1efc08.png)

#### Expected behaviour:

If there is a button there, it should be visible. Especially if both Integrated Crafting _and_ Integrated Terminals are installed.

____

#### Versions:

- Core: 1.17.0
- CC: 2.8.3
- Dynamics: 1.13.1
- Tunnels: 1.8.17
- Crafting: 1.0.26
- Terminals: 1.4.1
- Minecraft: 1.19.2
- Forge: 43.1.57

**Comment by rubensworks** [comment]
Thanks for reporting!
