### ISSUE TITLE
Game crashes when opening the Storage Terminal when using Roughly enough items

### ISSUE THREAD

**Issue by MohrJonas** [CyclopsMC/IntegratedTerminals#96]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Game crashes when opening the Storage Terminal when using Roughly enough items

#### Steps to reproduce the problem:

1. Install [Roughly enough items](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
2. Create a network consisting of 1 item interface facing a chest and 1 Storage terminal
3. Open the Storage terminal
4. Click on the item storage tab

#### Expected behaviour:

The storage tab should open

____

#### Versions:

- This mod: 1.19.2-1.4.1
- Minecraft: 1.19.2
- Forge: 43.1.47

#### Log file:
https://gist.github.com/MohrJonas/5ceef4ecbf348662eb4cf08190f977cd

**Comment by rubensworks** [comment]
Thanks for reporting!
