### ISSUE TITLE
Error while fml loading process

### ISSUE THREAD

**Issue by F4Yts** [CyclopsMC/IntegratedTerminals#97]
[crash-2022-12-12_17.38.30-fml.txt](https://github.com/CyclopsMC/IntegratedTerminals/files/10209600/crash-2022-12-12_17.38.30-fml.txt)

**Comment by rubensworks** [comment]
@F4Yts Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
