### ISSUE TITLE
JEI/REI crafting.

### ISSUE THREAD

**Issue by Ackmard** [CyclopsMC/IntegratedTerminals#98]
#### Issue type:

- :bug: Bug 

____

#### Short description:
When trying to craft with either JEI/REI the button to move items in the crafting table is red even if you do have the itms(REI says that you don't). The weird thing is that with JEI you can click the buttons and it will work. So JEI is kinda broken and REI is pretty much broken.

#### Steps to reproduce the problem:

1. Setup a network
2. Try to craft anything from JEI/REI while you have half the items in a chest
3. Red button and overlay
4. While using JEI you can still click the button and it will move half the items/With REI it's not gonna do anything.

#### Expected behaviour:

The button should be clickable and there shouldn't be an overlay over the items.

____

#### Versions:

- This mod: 1.4.3
- Minecraft: 1.18.2
- Forge: 40.2.0

**Comment by rubensworks** [comment]
Thanks for reporting!
